version: '3.9'

services:
  fyp-db:
    build:
        context: .
        dockerfile: Dockerfile.postgres
    container_name: fyp-db
    restart: always
    environment:
      POSTGRES_MULTIPLE_DATABASES: demo,fyp
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - fyp-db-data:/var/lib/postgresql/data

  fyp-keycloak:
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    container_name: fyp-keycloak
    restart: always
    volumes:
      - ./config/:/opt/keycloak/data/import:ro
    entrypoint: '/opt/keycloak/bin/kc.sh start-dev --import-realm'
    ports:
      - "8080:8080"
    depends_on:
      - fyp-db

  fyp-webapp:
    build: 
      context: fyp-webapp
      dockerfile: Dockerfile
    container_name: fyp-webapp
    volumes:
      - fyp-webapp-build:/app
    environment:
      DATABASE_URL: postgresql://fyp:fyp@fyp-db:5432/demo?schema=public&connect_timeout=60
    ports:
      - "3000:3000"
    depends_on:
      - fyp-db
      - fyp-keycloak
  fyp-nginx:
    build:
      context: nginx
      dockerfile: Dockerfile.nginx
    container_name: fyp-nginx
    volumes:
      - fyp-webapp-build:/app
      - ./certbot/www/:/var/www/certbot/:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fyp-webapp
      - fyp-keycloak
  fyp-certbot:
    container_name: fyp-certbot
    image: certbot/certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  fyp-db-data:
  fyp-webapp-build:
  data: {}