version: '3.9'

services:
  fyp-db:
    build:
        context: .
        dockerfile: Dockerfile.postgres
    container_name: fyp-db
    restart: always
    environment:
      POSTGRES_MULTIPLE_DATABASES: demo,fyp
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - fyp-db-data:/var/lib/postgresql/data

  fyp-keycloak:
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    container_name: fyp-keycloak
    restart: always
    volumes:
      - ./config/:/opt/keycloak/data/import:ro
    entrypoint: '/opt/keycloak/bin/kc.sh start --import-realm'
    ports:
      - "8080:8080"
    depends_on:
      - fyp-db

  fyp-webapp:
    build: 
      context: fyp-webapp
      dockerfile: Dockerfile
    container_name: fyp-webapp
    environment:
      DATABASE_URL: postgresql://fyp:fyp@fyp-db:5432/demo?schema=public&connect_timeout=60
    ports:
      - "3000:3000"
    depends_on:
      - fyp-db
      - fyp-keycloak
  fyp-nginx:
    image: jonasal/nginx-certbot:3
    container_name: fyp-nginx
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=edwardonionc0209@gmail.com
    volumes:
      - ./user_conf.d:/etc/nginx/user_conf.d
      - ./letsencrypt:/etc/letsencrypt
      - ./proxy_params:/etc/nginx/proxy_params:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fyp-webapp
      - fyp-keycloak

volumes:
  fyp-db-data:
