version: '3.9'

services:
  fyp-db:
    image: postgres:latest
    container_name: fyp-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - fyp-db-data:/var/lib/postgresql/data

  fyp-keycloak:
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    container_name: fyp-keycloak
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - fyp-db

volumes:
  fyp-db-data: