name: CI/CD Pipeline

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Set up SSH key
      run: |
        echo "${{ secrets.SSH_DEPLOY_KEY }}" > deploy_key.pem
        chmod 600 deploy_key.pem  

    - name: Git Pull on Server
      run: |
        ssh -o StrictHostKeyChecking=no -i deploy_key.pem ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << EOF
          cd ~/fyp/sporting-event-pwa
          # Ensure we're on the production branch
          git fetch --all
          git checkout production || git checkout -b production
          git reset --hard origin/production

          # Pull the latest changes
          git pull origin production

          docker-compose up -d --build
        EOF

    - name: Cleanup SSH Key
      run: rm -f deploy_key.pem

    