name: CI/CD Pipeline

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: Login to DockerHub
      uses: docker/login-action@v3.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

    - name: Build and push Docker images
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push
      
    - name: Deploy to Server
      run: |
        echo "${{ secrets.SSH_DEPLOY_KEY }}" > deploy_key.pem
        chmod 600 deploy_key.pem
        ssh -o StrictHostKeyChecking=no -i deploy_key.pem ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << EOF
          set -e  # Stop the script if any command fails
          # Install Docker Compose if it's not installed
          if ! command -v docker-compose &> /dev/null
          then
              echo "Installing Docker Compose..."
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
          fi
          cd /sporting-event-pwa
          docker-compose pull
          docker-compose up -d
        EOF
        rm -f deploy_key.pem 
