name: CI/CD Pipeline

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: Login to DockerHub
      uses: docker/login-action@v3.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

    - name: Build and push Docker images
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push
      
    - name: Deploy to Server
      run: |
        echo "${{ secrets.SSH_DEPLOY_KEY }}" > deploy_key.pem
        chmod 600 deploy_key.pem
        scp -o StrictHostKeyChecking=no -i deploy_key.pem build.tar.gz ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/tmp/build.tar.gz
        ssh -o StrictHostKeyChecking=no -i deploy_key.pem ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << EOF
          set -e  # Stop the script if any command fails
          sudo mv /tmp/build.tar.gz /sporting-event-pwa/build.tar.gz
          cd /sporting-event-pwa
          sudo tar -xzf build.tar.gz
          docker-compose pull
          docker-compose up -d
        EOF
        rm -f deploy_key.pem 
