name: CI/CD Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to Server
      if: github.ref == 'refs/heads/develop'
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_DEPLOY_KEY }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} 'mkdir -p /sporting-event-pwa/frontend'
        tar -czf build.tar.gz build/
        scp -o StrictHostKeyChecking=no -i ${{ secrets.SSH_DEPLOY_KEY }} build.tar.gz ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/sporting-event-pwa/frontend
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_DEPLOY_KEY }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} 'tar -xzf /sporting-event-pwa/frontend/build.tar.gz -C /sporting-event-pwa/frontend && rm /sporting-event-pwa/frontend/build.tar.gz'
